services:
  client:
    image: prwt-client
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
